# Generated by Django 6.0.1 on 2026-01-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='public_key',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
