# Generated by Django 6.0.1 on 2026-01-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_device_public_key'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='user_devices',
        ),
    ]
