# Generated by Django 6.0.1 on 2026-01-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_device_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
