# Generated by Django 6.0.1 on 2026-01-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_device_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='public_key',
        ),
        migrations.AddField(
            model_name='device',
            name='public_key_pem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
