# Generated by Django 6.0.1 on 2026-01-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_device_public_key_device_public_key_pem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
